[package]
name = "momentum"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
overlap = { path = "../overlap" }
price = { path = "../price" }
utils = { path = "../utils" }
