[workspace]
members = [
"core",
"indicators/momentum",
"indicators/trend",
"indicators/volatility",
"indicators/volume",
"patterns/candlestick",
"price",
"strategies/base",
"strategies/trend_follow",
"strategies/shared/stop_loss",
"utils"
]

[profile.release]
opt-level = 'z'
lto = true
