[workspace]
members = [
"core",
"indicators/momentum",
"indicators/trend",
"indicators/volatility",
"indicators/volume",
"patterns/candlestick",
"price",
"strategies/base",
"strategies/trend_follow",
"strategies/stop_loss",
"strategies/signal",
"strategies/regime_filter",
"strategies/shared",
"strategies/volume_filter"
]

[profile.release]
opt-level = 3
lto = true
