[workspace]
members = [
"core",
"indicators/momentum",
"indicators/trend",
"indicators/volatility",
"indicators/volume",
"patterns",
"price",
"strategies/base",
"utils"
]

[profile.release]
opt-level = "s"
