[package]
name = "exit"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
core = { path = "../../core" }
candlestick = { path = "../../patterns/candlestick" }
shared = { path = "../shared" }