[package]
name = "trend_follow"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
base = { path = "../base" }
trend = { path = "../../indicators/trend" }

[lib]
crate-type = ["cdylib", "rlib"]