[package]
name = "trend_follow"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "*"
core = { path = "../../core" }
base = { path = "../base" }
stop_loss = { path = "../stop_loss" }
filter = { path = "../filter" }
shared = { path = "../shared" }
volatility = { path = "../../indicators/volatility" }

[lib]
crate-type = ["cdylib"]
