[package]
name = "trend_follow"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
base = { path = "../base" }
stop_loss = { path = "../stop_loss" }
filter = { path = "../filter" }
shared = { path = "../shared" }
signal = { path = "../signal" }
exit = { path = "../exit" }

[lib]
crate-type = ["cdylib"]
