[package]
name = "trend_follow"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
base = { path = "../base" }
stop_loss = { path = "../stop_loss" }
regime_filter = { path = "../regime_filter" }
volume_filter = { path = "../volume_filter" }
shared = { path = "../shared" }
signal = { path = "../signal" }
exit = { path = "../exit" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
