[package]
name = "trend_follow"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "*"
core = { path = "../../core" }
base = { path = "../base" }
trend = { path = "../../indicators/trend" }
stop_loss = { path = "../shared/stop_loss" }

[lib]
crate-type = ["cdylib"]